// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Readline = require("readline");

var options = {
  input: (process.stdin),
  output: (process.stdout)
};

var readline = Readline.createInterface(options);

var yes = (/yes|y/gi);

var no = (/no|n/gi);

readline.question("Is ReasonML and BuckleScript awesome? ", (function (answer) {
        if (yes.test(answer)) {
          console.log("You know it!");
        } else if (no.test(answer)) {
          console.log("You need to revaluate your answer");
        } else {
          console.log(" I don\'t have a variant for your answer 😦: " + (String(answer) + " "));
        }
        readline.close();
        return /* () */0;
      }));

exports.options = options;
exports.readline = readline;
exports.yes = yes;
exports.no = no;
/* options Not a pure module */
