version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install global dev env
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}  
      - run:
          name: Bootstrap lerna throughout the packages
          command: node_modules/.bin/lerna bootstrap
      - run:
          name: Build all packages
          command: yarn build
      - run:
          name: Trigger the test suite over all the packages
          command: yarn test
