// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var ReactTransitionGroup = require("react-transition-group");

function make($staropt$star, timeout, $staropt$star$1, $staropt$star$2, $staropt$star$3, $staropt$star$4, $staropt$star$5, $staropt$star$6, classNames, children) {
  var in_ = $staropt$star !== undefined ? $staropt$star : false;
  var className = $staropt$star$1 !== undefined ? $staropt$star$1 : "";
  var mountOnEnter = $staropt$star$2 !== undefined ? $staropt$star$2 : false;
  var unmountOnExit = $staropt$star$3 !== undefined ? $staropt$star$3 : false;
  var appear = $staropt$star$4 !== undefined ? $staropt$star$4 : false;
  var enter = $staropt$star$5 !== undefined ? $staropt$star$5 : true;
  var exit = $staropt$star$6 !== undefined ? $staropt$star$6 : true;
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.CSSTransition, {
              in: in_,
              timeout: timeout,
              classNames: classNames,
              className: className,
              mountOnEnter: mountOnEnter,
              unmountOnExit: unmountOnExit,
              appear: appear,
              enter: enter,
              exit: exit
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
