// Generated by BUCKLESCRIPT VERSION 4.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var StyletronReact = require("styletron-react");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");
var StyletronEngineAtomic = require("styletron-engine-atomic");

var Core = /* module */[];

function make(options, _) {
  return new StyletronEngineAtomic.Client(Js_null_undefined.fromOption(options));
}

var Client = /* module */[/* make */make];

function makeStyledClass(base, rule) {
  return StyletronReact.styled(base[1], rule);
}

function makeStyled(base, rule, props, children) {
  var reactClass = StyletronReact.styled(base[1], rule);
  return ReasonReact.wrapJsForReason(reactClass, props, children);
}

function makeStyledComponent(rule, component, make, props, children) {
  var reactClass = ReasonReact.wrapReasonForJs(component, (function (jsProps) {
          return Curry._2(make, jsProps, children);
        }));
  var styledClass = StyletronReact.styled(reactClass, rule);
  return ReasonReact.wrapJsForReason(styledClass, props, children);
}

function make$1($staropt$star, children) {
  var value = $staropt$star !== undefined ? Js_primitive.valFromOption($staropt$star) : new StyletronEngineAtomic.Client(Js_null_undefined.fromOption(undefined));
  return ReasonReact.wrapJsForReason(StyletronReact.Provider, {
              value: value
            }, children);
}

var Provider = /* module */[/* make */make$1];

var React = /* module */[
  /* makeStyledClass */makeStyledClass,
  /* makeStyled */makeStyled,
  /* makeStyledComponent */makeStyledComponent,
  /* Provider */Provider
];

exports.Core = Core;
exports.Client = Client;
exports.React = React;
/* ReasonReact Not a pure module */
