// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, lang, source, children) {
  return ReasonReact.wrapJsForReason(Spectacle.CodePane, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, {
                  lang: lang,
                  source: source
                }), children);
}

exports.make = make;
/* spectacle Not a pure module */
