// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function componentPlaygroundThemeToJs(theme) {
  if (theme) {
    return "dark";
  } else {
    return "light";
  }
}

function make(code, previewBackgroundColor, theme, scope, children) {
  var tmp = { };
  if (code !== undefined) {
    tmp.code = Js_primitive.valFromOption(code);
  }
  if (previewBackgroundColor !== undefined) {
    tmp.previewBackgroundColor = Js_primitive.valFromOption(previewBackgroundColor);
  }
  var tmp$1 = Js_option.map(componentPlaygroundThemeToJs, theme);
  if (tmp$1 !== undefined) {
    tmp.theme = Js_primitive.valFromOption(tmp$1);
  }
  if (scope !== undefined) {
    tmp.scope = Js_primitive.valFromOption(scope);
  }
  return ReasonReact.wrapJsForReason(Spectacle.ComponentPlayground, tmp, children);
}

exports.componentPlaygroundThemeToJs = componentPlaygroundThemeToJs;
exports.make = make;
/* spectacle Not a pure module */
