// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, src, alt, display, width, children) {
  var tmp = {
    src: src
  };
  if (alt !== undefined) {
    tmp.alt = Js_primitive.valFromOption(alt);
  }
  if (display !== undefined) {
    tmp.display = Js_primitive.valFromOption(display);
  }
  if (width !== undefined) {
    tmp.width = Js_primitive.valFromOption(width);
  }
  return ReasonReact.wrapJsForReason(Spectacle.Image, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, tmp), children);
}

exports.make = make;
/* spectacle Not a pure module */
