// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var BaseProps$BsSpectacle = require("../BaseProps.js");

var include = BaseProps$BsSpectacle.MakeBaseComponent(/* module */[/* ListItem */Spectacle.ListItem]);

var make = include[0];

exports.make = make;
/* include Not a pure module */
