// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, ordered, reversed, start, type_, children) {
  var tmp = { };
  if (ordered !== undefined) {
    tmp.ordered = Js_primitive.valFromOption(ordered);
  }
  if (reversed !== undefined) {
    tmp.reversed = Js_primitive.valFromOption(reversed);
  }
  if (start !== undefined) {
    tmp.start = Js_primitive.valFromOption(start);
  }
  if (type_ !== undefined) {
    tmp.type = Js_primitive.valFromOption(type_);
  }
  return ReasonReact.wrapJsForReason(Spectacle.List, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, tmp), children);
}

exports.make = make;
/* spectacle Not a pure module */
