// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Js_option = require("bs-platform/lib/js/js_option.js");
var Spectacle = require("spectacle");
var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var BaseProps$BsSpectacle = require("../BaseProps.js");

var jsMapperConstantArray = /* array */[
  /* tuple */[
    -1055161979,
    "bold"
  ],
  /* tuple */[
    -136827821,
    "strikethrough"
  ],
  /* tuple */[
    107228912,
    "italic"
  ],
  /* tuple */[
    131142924,
    "underline"
  ]
];

function sTypeToJs(param) {
  return Js_mapperRt.binarySearch(4, param, jsMapperConstantArray);
}

function sTypeFromJs(param) {
  return Js_mapperRt.revSearch(4, jsMapperConstantArray, param);
}

var mapSTypeToJs = sTypeToJs;

function make(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, type_, children) {
  var tmp = { };
  var tmp$1 = Js_option.map(mapSTypeToJs, type_);
  if (tmp$1 !== undefined) {
    tmp.type = Js_primitive.valFromOption(tmp$1);
  }
  return ReasonReact.wrapJsForReason(Spectacle.S, BaseProps$BsSpectacle.extendProps(italic, bold, caps, margin, padding, textColor, textSize, textAlign, textFont, bgColor, bgImage, bgSize, bgPosition, bgRepeat, bgDarken, overflow, height, tmp), children);
}

exports.sTypeToJs = sTypeToJs;
exports.sTypeFromJs = sTypeFromJs;
exports.mapSTypeToJs = mapSTypeToJs;
exports.make = make;
/* spectacle Not a pure module */
