// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Spectacle = require("spectacle");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");

function make(font, googleFont, weight, italic, children) {
  var tmp = { };
  if (font !== undefined) {
    tmp.font = Js_primitive.valFromOption(font);
  }
  if (googleFont !== undefined) {
    tmp.googleFont = Js_primitive.valFromOption(googleFont);
  }
  if (weight !== undefined) {
    tmp.weight = Js_primitive.valFromOption(weight);
  }
  if (italic !== undefined) {
    tmp.italic = Js_primitive.valFromOption(italic);
  }
  return ReasonReact.wrapJsForReason(Spectacle.Typeface, tmp, children);
}

exports.make = make;
/* spectacle Not a pure module */
