// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


var maxMappings = /* record */[
  /* spellId */0,
  /* patientId */1,
  /* arrivalDate */5,
  /* arrivalTime */7,
  /* departureDate */8,
  /* departureTime */10,
  /* ward */4,
  /* specialty */14,
  /* consultant */11
];

var sathMappings = /* record */[
  /* spellId */1,
  /* patientId */2,
  /* arrivalDate */3,
  /* arrivalTime */4,
  /* departureDate */5,
  /* departureTime */6,
  /* ward */12,
  /* specialty */13,
  /* consultant */15
];

var belgiumMappings = /* record */[
  /* spellId */2,
  /* patientId */1,
  /* arrivalDate */3,
  /* arrivalTime */4,
  /* departureDate */5,
  /* departureTime */6,
  /* ward */12,
  /* specialty */13,
  /* consultant */15
];

var careMappings = /* record */[
  /* spellId */1,
  /* patientId */0,
  /* arrivalDate */4,
  /* arrivalTime */5,
  /* departureDate */14,
  /* departureTime */15,
  /* ward */10,
  /* specialty */9,
  /* consultant */12
];

var mappings = maxMappings;

exports.sathMappings    = sathMappings;
exports.belgiumMappings = belgiumMappings;
exports.careMappings    = careMappings;
exports.maxMappings     = maxMappings;
exports.mappings        = mappings;
/* No side effect */
