// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var Table       = require("./Table.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function str(prim) {
  return prim;
}

var rows = /* array */[
  {
    a: "11",
    b: "12"
  },
  {
    a: "21",
    b: "22"
  }
];

var MyRows = /* module */[/* rows */rows];

var component = ReasonReact.statelessComponent("DemoTable");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var MyTable = Table.Make(MyRows);
      return ReasonReact.element(/* None */0, /* None */0, Curry._2(MyTable[/* Table */0][/* make */0], /* record */[
                      /* headerHeight */20,
                      /* columnWidth */200,
                      /* height */300,
                      /* rowHeight */30,
                      /* columnSpecs : :: */[
                        /* record */[
                          /* label */"a",
                          /* dataKey */"a",
                          /* width */80
                        ],
                        /* :: */[
                          /* record */[
                            /* label */"b",
                            /* dataKey */"b",
                            /* width */80
                          ],
                          /* [] */0
                        ]
                      ]
                    ], /* array */[]));
    });
  return newrecord;
}

exports.str       = str;
exports.MyRows    = MyRows;
exports.component = component;
exports.make      = make;
/* component Not a pure module */
