// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("bs-jest/lib/js/src/jest.js");

describe("calculating the table width", (function () {
        return Jest.test("happy path", (function () {
                      return Jest.Expect[/* toBe */2](/* true */1, Jest.Expect[/* expect */0](/* true */1));
                    }));
      }));

/*  Not a pure module */
