// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactTransitionGroup = require("react-transition-group");

function stateOfString(str) {
  switch (str) {
    case "entered" : 
        return /* Entered */1;
    case "entering" : 
        return /* Entering */0;
    case "exited" : 
        return /* Exited */3;
    case "exiting" : 
        return /* Exiting */2;
    default:
      return /* NotTransitioning */4;
  }
}

function stringOfState(str) {
  switch (str) {
    case 0 : 
        return "entering";
    case 1 : 
        return "entered";
    case 2 : 
        return "exiting";
    case 3 : 
        return "exited";
    case 4 : 
        return "Not";
    
  }
}

function make($staropt$star, timeout, $staropt$star$1, $staropt$star$2, children) {
  var in_ = $staropt$star !== undefined ? $staropt$star : false;
  var component = $staropt$star$1 !== undefined ? $staropt$star$1 : "div";
  var className = $staropt$star$2 !== undefined ? $staropt$star$2 : "";
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.Transition, {
              in: in_,
              component: component,
              timeout: timeout,
              className: className
            }, (function (strState, _) {
                return Curry._1(children, stateOfString(strState));
              }));
}

exports.stateOfString = stateOfString;
exports.stringOfState = stringOfState;
exports.make = make;
/* ReasonReact Not a pure module */
