// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var ReactTransitionGroup = require("react-transition-group");

function make($staropt$star, $staropt$star$1, children) {
  var className = $staropt$star !== undefined ? $staropt$star : "";
  var component = $staropt$star$1 !== undefined ? $staropt$star$1 : "div";
  return ReasonReact.wrapJsForReason(ReactTransitionGroup.TransitionGroup, {
              component: component,
              className: className
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
