// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Default = require("spectacle/lib/themes/default");

function colorsDefinitionToJs(param) {
  return {
          primary: param[/* primary */0],
          secondary: param[/* secondary */1],
          tertiary: param[/* tertiary */2],
          quarternary: param[/* quarternary */3]
        };
}

function fontDefinitionToJs(param) {
  return {
          name: param[/* name */0],
          googleFont: param[/* googleFont */1],
          styles: param[/* styles */2]
        };
}

function fontsDefinitionToJs(fonts) {
  return {
          primary: fontDefinitionToJs(fonts[/* primary */0]),
          secondary: fontDefinitionToJs(fonts[/* secondary */1]),
          tertiary: fontDefinitionToJs(fonts[/* tertiary */2])
        };
}

function simpleFont(name) {
  return /* record */[
          /* name */name,
          /* googleFont */false,
          /* styles : array */[]
        ];
}

function createTheme(colors, fonts) {
  return Default.default(colorsDefinitionToJs(colors), fontsDefinitionToJs(fonts));
}

exports.simpleFont = simpleFont;
exports.createTheme = createTheme;
/* spectacle/lib/themes/default Not a pure module */
