type t = [
  | #single
  | #dashDotStroked
  | #dashed
  | #dashSmallGap
  | #dotDash
  | #dotDotDash
  | #dotted
  | #double
  | #doubleWave
  | #inset
  | #nil
  | #none
  | #outset
  | #thick
  | #thickThinLargeGap
  | #thickThinMediumGap
  | #thickThinSmallGap
  | #thinThickLargeGap
  | #thinThickMediumGap
  | #thinThickSmallGap
  | #thinThickThinLargeGap
  | #thinThickThinMediumGap
  | #thinThickThinSmallGap
  | #threeDEmboss
  | #threeDEngrave
  | #triple
  | #wave
]
