type t =
  | @as("decimal") Decimal
  | @as("upperRoman") UpperRoman
  | @as("lowerRoman") LowerRoman
  | @as("upperLetter") UpperLetter
  | @as("lowerLetter") LowerLetter
  | @as("ordinal") Ordinal
  | @as("cardinalText") CardinalText
  | @as("ordinalText") OrdinalText
  | @as("hex") Hex
  | @as("chicago") Chicago
  | @as("ideographDigital") IdeographDigital
  | @as("japaneseCounting") JapaneseCounting
  | @as("aiueo") Aiueo
  | @as("iroha") Iroha
  | @as("decimalFullWidth") DecimalFullWidth
  | @as("decimalHalfWidth") DecimalHalfWidth
  | @as("japaneseLegal") JapaneseLegal
  | @as("japaneseDigitalTenThousand") JapaneseDigitalTenThousand
  | @as("decimalEnclosedCircle") DecimalEnclosedCircle
  | @as("decimalFullWidth2") DecimalFullWidth2
  | @as("aiueoFullWidth") AiueoFullWidth
  | @as("irohaFullWidth") IrohaFullWidth
  | @as("decimalZero") DecimalZero
  | @as("bullet") Bullet
  | @as("ganada") Ganada
  | @as("chosung") Chosung
  | @as("decimalEnclosedFullstop") DecimalEnclosedFullStop
  | @as("decimalEnclosedParen") DecimalEnclosedParen
  | @as("decimalEnclosedCircleChinese") DecimalEnclosedCircleChinese
  | @as("ideographEnclosedCircle") IdeographEnclosedCircle
  | @as("ideographTraditional") IdeographTraditional
  | @as("ideographZodiac") IdeographZodiac
  | @as("ideographZodiacTraditional") IdeographZodiacTraditional
  | @as("taiwaneseCounting") TaiwaneseCounting
  | @as("ideographLegalTraditional") IdeographLegalTraditional
  | @as("taiwaneseCountingThousand") TaiwaneseCountingThousand
  | @as("taiwaneseDigital") TaiwaneseDigital
  | @as("chineseCounting") ChineseCounting
  | @as("chineseLegalSimplified") ChineseLegalSimplified
  | @as("chineseCountingThousand") ChineseCountingTenThousand
  | @as("koreanDigital") KoreanDigital
  | @as("koreanCounting") KoreanCounting
  | @as("koreanLegal") KoreanLegal
  | @as("koreanDigital2") KoreanDigital2
  | @as("vietnameseCounting") VietnameseCounting
  | @as("russianLower") RussianLower
  | @as("russianUpper") RussianUpper
  | @as("none") None
  | @as("numberInDash") NumberInDash
  | @as("hebrew1") Hebrew1
  | @as("hebrew2") Hebrew2
  | @as("arabicAlpha") ArabicAlpha
  | @as("arabicAbjad") ArabicAbjad
  | @as("hindiVowels") HindiVowels
  | @as("hindiConsonants") HindiConsonants
  | @as("hindiNumbers") HindiNumbers
  | @as("hindiCounting") HindiCounting
  | @as("thaiLetters") ThaiLetters
  | @as("thaiNumbers") ThaiNumbers
  | @as("thaiCounting") ThaiCounting
  | @as("bahtText") BahtText
  | @as("dollarText") DollarText
