// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("./parser/json.cjs");
var Test_runners = require("../test_runners.cjs");

Test_runners.runTests(Json.parse, (function (input, param) {
        return "[JSON Number] Run with \"" + input + "\"";
      }), [
      [
        "1234",
        {
          TAG: /* Number */1,
          _0: "1234"
        },
        ""
      ],
      [
        "-1234",
        {
          TAG: /* Number */1,
          _0: "-1234"
        },
        ""
      ],
      [
        "-0",
        {
          TAG: /* Number */1,
          _0: "-0"
        },
        ""
      ],
      [
        "0",
        {
          TAG: /* Number */1,
          _0: "0"
        },
        ""
      ],
      [
        "1234.1234",
        {
          TAG: /* Number */1,
          _0: "1234.1234"
        },
        ""
      ],
      [
        "1234.1e1",
        {
          TAG: /* Number */1,
          _0: "1234.1e1"
        },
        ""
      ],
      [
        "0.12E-6543",
        {
          TAG: /* Number */1,
          _0: "0.12E-6543"
        },
        ""
      ]
    ]);

Test_runners.runTests(Json.parse, (function (input, param) {
        return "[JSON Number] Partial with \"" + input + "\"";
      }), [
      [
        "0.12E-6543hello",
        {
          TAG: /* Number */1,
          _0: "0.12E-6543"
        },
        "hello"
      ],
      [
        "111hello",
        {
          TAG: /* Number */1,
          _0: "111"
        },
        "hello"
      ],
      [
        "-533.1hello",
        {
          TAG: /* Number */1,
          _0: "-533.1"
        },
        "hello"
      ],
      [
        "-1234.1..1hello",
        {
          TAG: /* Number */1,
          _0: "-1234.1"
        },
        "..1hello"
      ]
    ]);

Test_runners.runFailureTests(Json.parse, (function (input) {
        return "[JSON Number] Run with \"" + input + "\"";
      }), [
      "_-1",
      "--0.12E-6543",
      "a0.12"
    ]);

/*  Not a pure module */
