// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("./parser/json.cjs");
var Test_runners = require("../test_runners.cjs");

Test_runners.runTests(Json.parse, (function (input, param) {
        return "[JSON] True \"" + input + "\"";
      }), [
      [
        "true",
        /* True */1,
        ""
      ],
      [
        "false",
        /* False */2,
        ""
      ]
    ]);

Test_runners.runFailureTests(Json.parse, (function (input) {
        return "[JSON] Invalid true \"" + input + "\"";
      }), [
      "ttrue",
      "-true"
    ]);

Test_runners.runFailureTests(Json.parse, (function (input) {
        return "[JSON] Invalid false \"" + input + "\"";
      }), [
      "ffalse",
      "{false"
    ]);

/*  Not a pure module */
