// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json = require("./parser/json.cjs");
var Test_runners = require("../test_runners.cjs");

Test_runners.runTests(Json.parse, (function (input, param) {
        return "[JSON Array] \"" + input + "\"";
      }), [
      [
        "[]",
        {
          TAG: /* Array */3,
          _0: /* [] */0
        },
        ""
      ],
      [
        "[\"1\"]",
        {
          TAG: /* Array */3,
          _0: {
            hd: {
              TAG: /* String */2,
              _0: "1"
            },
            tl: /* [] */0
          }
        },
        ""
      ],
      [
        "[1]",
        {
          TAG: /* Array */3,
          _0: {
            hd: {
              TAG: /* Number */1,
              _0: "1"
            },
            tl: /* [] */0
          }
        },
        ""
      ],
      [
        "[1, 2]",
        {
          TAG: /* Array */3,
          _0: {
            hd: {
              TAG: /* Number */1,
              _0: "1"
            },
            tl: {
              hd: {
                TAG: /* Number */1,
                _0: "2"
              },
              tl: /* [] */0
            }
          }
        },
        ""
      ],
      [
        "[1,2]",
        {
          TAG: /* Array */3,
          _0: {
            hd: {
              TAG: /* Number */1,
              _0: "1"
            },
            tl: {
              hd: {
                TAG: /* Number */1,
                _0: "2"
              },
              tl: /* [] */0
            }
          }
        },
        ""
      ],
      [
        "[1, \"2\"]",
        {
          TAG: /* Array */3,
          _0: {
            hd: {
              TAG: /* Number */1,
              _0: "1"
            },
            tl: {
              hd: {
                TAG: /* String */2,
                _0: "2"
              },
              tl: /* [] */0
            }
          }
        },
        ""
      ],
      [
        "[null, \"1\"]",
        {
          TAG: /* Array */3,
          _0: {
            hd: /* Null */0,
            tl: {
              hd: {
                TAG: /* String */2,
                _0: "1"
              },
              tl: /* [] */0
            }
          }
        },
        ""
      ],
      [
        "[false, true, 14.2]",
        {
          TAG: /* Array */3,
          _0: {
            hd: /* False */2,
            tl: {
              hd: /* True */1,
              tl: {
                hd: {
                  TAG: /* Number */1,
                  _0: "14.2"
                },
                tl: /* [] */0
              }
            }
          }
        },
        ""
      ],
      [
        "[      false,     true, 14.2]",
        {
          TAG: /* Array */3,
          _0: {
            hd: /* False */2,
            tl: {
              hd: /* True */1,
              tl: {
                hd: {
                  TAG: /* Number */1,
                  _0: "14.2"
                },
                tl: /* [] */0
              }
            }
          }
        },
        ""
      ],
      [
        "[      false,     true,\n\n  14.2]",
        {
          TAG: /* Array */3,
          _0: {
            hd: /* False */2,
            tl: {
              hd: /* True */1,
              tl: {
                hd: {
                  TAG: /* Number */1,
                  _0: "14.2"
                },
                tl: /* [] */0
              }
            }
          }
        },
        ""
      ],
      [
        "[1, [1, true, [3, null]]]",
        {
          TAG: /* Array */3,
          _0: {
            hd: {
              TAG: /* Number */1,
              _0: "1"
            },
            tl: {
              hd: {
                TAG: /* Array */3,
                _0: {
                  hd: {
                    TAG: /* Number */1,
                    _0: "1"
                  },
                  tl: {
                    hd: /* True */1,
                    tl: {
                      hd: {
                        TAG: /* Array */3,
                        _0: {
                          hd: {
                            TAG: /* Number */1,
                            _0: "3"
                          },
                          tl: {
                            hd: /* Null */0,
                            tl: /* [] */0
                          }
                        }
                      },
                      tl: /* [] */0
                    }
                  }
                }
              },
              tl: /* [] */0
            }
          }
        },
        ""
      ]
    ]);

/*  Not a pure module */
